name: CraftExtinguisher
main: com.electro2560.dev.craftextinguisher.CraftExtinguisher
author: ElectroBoy2560
website: http://dev.electro2560.com/
version: 1.2.0
commands:
  craftextinguish:
    description: Used to configure plugin.
    aliases: [ce]