name: CraftExtinguisher
main: com.electro2560.dev.craftextinguisher.CraftExtinguisher
author: ElectroBoy2560
website: http://dev.electro2560.com/
version: 1.2.1
commands:
  craftextinguish:
    description: Used to configure plugin.
    aliases: [ce]
    permission: craftextinguisher.admin
permissions:
  craftextinguisher.use:
    description: Access to use craft extinguisher
    default: true
  craftextinguisher.admin:
    description: Access to admin commands and update checker
    default: op